### PR TITLE
refresh auction balance and my credit balance

### PR DESCRIPTION
**Pull request by ba1ciu**
I ended up using `refetch`, but there's a thing called `polling` in Apollo client, which would be a better fit for this. Unfortunatelly, I didn't manage to get it working with. If you want you can try using it @PiranavanShanmugavadivelu

https://www.apollographql.com/docs/react/data/queries/#polling

### CODE REVIEW

**Comment by ba1ciu** [comment]
> @ba1ciu A small suggestion. What if we reload the data when the Retire credits successfully completed instead of using timeout? 🤔

It's not that simple, because we're not sure that indexed data has been already updated, there might be a delay between transaction passing successfully and indexer actually picking it up, so imo refetching periodically is a better solution.

**Comment by PiranavanShanmugavadivelu** [comment]
> > @ba1ciu A small suggestion. What if we reload the data when the Retire credits successfully completed instead of using timeout? 🤔
> 
> It's not that simple, because we're not sure that indexed data has been already updated, there might be a delay between transaction passing successfully and indexer actually picking it up, so imo refetching periodically is a better solution.

@ba1ciu ,No, I mean from the front end side, Trigger reload in the retire credits success.

**Comment by ba1ciu** [comment]
> > > @ba1ciu A small suggestion. What if we reload the data when the Retire credits successfully completed instead of using timeout? 🤔
> > 
> > 
> > It's not that simple, because we're not sure that indexed data has been already updated, there might be a delay between transaction passing successfully and indexer actually picking it up, so imo refetching periodically is a better solution.
> 
> @ba1ciu ,No, I mean from the front end side, Trigger reload in the retire credits success.

Yeah, I know :) It's just, if we reload immediately after we get a successful response from blockchain, there's no guarantee that it will return updated data, it can take some more time for query to take effect.

**Comment by PiranavanShanmugavadivelu** [comment]
> > > > @ba1ciu A small suggestion. What if we reload the data when the Retire credits successfully completed instead of using timeout? 🤔
> > > 
> > > 
> > > It's not that simple, because we're not sure that indexed data has been already updated, there might be a delay between transaction passing successfully and indexer actually picking it up, so imo refetching periodically is a better solution.
> > 
> > 
> > @ba1ciu ,No, I mean from the front end side, Trigger reload in the retire credits success.
> 
> Yeah, I know :) It's just, if we reload immediately after we get a successful response from blockchain, there's no guarantee that it will return updated data, it can take some more time for query to take effect.

Oh ok, Then this is the better way 😄

**Pull request merged**
