### PR TITLE
Fix whitespace for Make 4.3

### PR DESCRIPTION
**Pull request by freshe4qa**

### CODE REVIEW

**Comment by gjermundgaraba** [comment]
Hi @freshe4qa! Thanks for the PR! Would you mind explaining what this change actually does and why it is needed? :)

**Comment by freshe4qa** [comment]
Optimizing for the new version

**Comment by gjermundgaraba** [comment]
@freshe4qa can you please be more specific? Optimizing how? Solving what problem? I just need to understand what I am merging here :)

**Comment by freshe4qa** [comment]
Make 4.3 will only add a space when += is used if the variable it is used on exists. Using += on a non-existing variable would previously create a variable starting with a space.

**Review by gjermundgaraba — APPROVED** [review]

**Comment by gjermundgaraba** [comment]
Thanks for this @freshe4qa :rocket:

**Comment by freshe4qa** [comment]
Always glad to help

**Pull request merged**
