### PR TITLE
use cometbft

### PR DESCRIPTION
**Pull request by faddat**
https://github.com/notional-labs/wasmd/releases/tag/v0.31.x-sdk47x

### CODE REVIEW

**Comment by gjermundgaraba** [comment]
@faddat seems like it doesn't build properly. Any ideas?

**Comment by faddat** [comment]
Actually yes, I had forgotten to apply patches to the SDK and IBC.

**Comment by gjermundgaraba** [comment]
Hmm, interesting. The smoke tests that spin up the chain locally seem to be unhappy about something. The logs don't tell me much though, just that there is no node on the port it expects. Are you able to spin up a local node using `make serve`?

**Comment by gjermundgaraba** [comment]
This has been resolved through other PRs now. Closing. Thanks for the work in any case, it was useful :)

**Pull request closed without merging**
